// <auto-generated />
using System;
using Bookworm_Society_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookworm_Society_API.Migrations
{
    [DbContext(typeof(Bookworm_SocietyDbContext))]
    [Migration("20250418224830_UpdateBookSeedData")]
    partial class UpdateBookSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookBookClub", b =>
                {
                    b.Property<int>("BookClubsId")
                        .HasColumnType("integer");

                    b.Property<int>("HaveReadId")
                        .HasColumnType("integer");

                    b.HasKey("BookClubsId", "HaveReadId");

                    b.HasIndex("HaveReadId");

                    b.ToTable("BookClubsHaveReadBook", (string)null);
                });

            modelBuilder.Entity("BookClubUser", b =>
                {
                    b.Property<int>("MemberBookClubsId")
                        .HasColumnType("integer");

                    b.Property<int>("MembersId")
                        .HasColumnType("integer");

                    b.HasKey("MemberBookClubsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("UserBookClubMembership", (string)null);
                });

            modelBuilder.Entity("BookVotingSession", b =>
                {
                    b.Property<int>("VotingBooksId")
                        .HasColumnType("integer");

                    b.Property<int>("VotingSessionsId")
                        .HasColumnType("integer");

                    b.HasKey("VotingBooksId", "VotingSessionsId");

                    b.HasIndex("VotingSessionsId");

                    b.ToTable("VotingSessionBooks", (string)null);
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Harper",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Frank",
                            LastName = "Herbert"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Gillian",
                            LastName = "Flynn"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Markus",
                            LastName = "Zusak"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Stieg",
                            LastName = "Larsson"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Shirley",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Paulo",
                            LastName = "Coelho"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Bram",
                            LastName = "Stoker"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "J.D.",
                            LastName = "Salinger"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Cormac",
                            LastName = "McCarthy"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "J.K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AuthorId = 1,
                            Description = "One of the best-loved stories of all time, To Kill a Mockingbird has been translated into more than forty languages, sold more than forty million copies worldwide, served as the basis for an enormously popular motion picture, and was voted one of the best novels of the twentieth century by librarians across the country. A gripping, heart-wrenching, and wholly remarkable coming-of-age tale in a South poisoned by virulent prejudice, it views a world of great beauty and savage iniquities through the eyes of a young girl, as her father — a crusading local lawyer — risks everything to defend a black man unjustly accused of a terrible crime.",
                            GenreId = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/81aY1lxk+9L._SL1500_.jpg",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 102,
                            AuthorId = 2,
                            Description = "First published over 50 years ago, J.R.R. Tolkien's 'The Hobbit' has become one of the best-loved books of all time. Now Tolkien's fantasy classic has been adapted into a fully painted graphic novel.\r\n\r\n'The Hobbit' is the story of Bilbo Baggins…a quiet and contented hobbit whose life is turned upside down when he joins the wizard Gandalf and thirteen dwarves on their quest to reclaim the dwarves' stolen treasure. It is a journey fraught with danger – and in the end it is Bilbo alone who must face the guardian of this treasure, the most-dreaded dragon Smaug.\r\n\r\nIllustrated in full colour throughout, and accompanied by the carefully abridged text of the original novel, this handsome authorised edition will introduce new generations to a magical masterpiece – and be treasured by Hobbit fans of all ages, everywhere.",
                            GenreId = 2,
                            ImageUrl = "https://m.media-amazon.com/images/I/71mK6W2wMrL._SL1500_.jpg",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 103,
                            AuthorId = 3,
                            Description = "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...\r\n\r\nWhen House Atreides is betrayed, the destruction of Paul’s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad’Dib, he will bring to fruition humankind’s most ancient and unattainable dream.",
                            GenreId = 3,
                            ImageUrl = "https://m.media-amazon.com/images/I/71+IVP4wnEL._SL1500_.jpg",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 104,
                            AuthorId = 4,
                            Description = "Who are you?\r\nWhat have we done to each other?\r\n\r\nThese are the questions Nick Dunne finds himself asking on the morning of his fifth wedding anniversary when his wife Amy suddenly disappears. The police suspect Nick. Amy's friends reveal that she was afraid of him, that she kept secrets from him. He swears it isn't true. A police examination of his computer shows strange searches. He says they weren't made by him. And then there are the persistent calls on his mobile phone.\r\n\r\nSo what did happen to Nick's beautiful wife?",
                            GenreId = 4,
                            ImageUrl = "https://m.media-amazon.com/images/I/61mcHA1yJLL._SL1141_.jpg",
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 105,
                            AuthorId = 5,
                            Description = "Pride and Prejudice has charmed generations of readers for more than two centuries. Jane Austen's much-adapted novel is famed for its witty, spirited heroine, sensational romances, and deft remarks on the triumphs and pitfalls of social convention. Author Jane Austen (1775-1817) was an English novelist whose works of social realism achieved unprecedented critical and popular success, though Austen herself remained an anonymous writer throughout her life.",
                            GenreId = 5,
                            ImageUrl = "https://m.media-amazon.com/images/I/51zkOaWMu7S._SL1500_.jpg",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 106,
                            AuthorId = 6,
                            Description = "HERE IS A SMALL FACT:\r\n\r\nYOU ARE GOING TO DIE.\r\n\r\n1939. Nazi Germany. The country is holding its breath. Death has never been busier.\r\n\r\nLiesel, a nine-year-old girl, is living with her foster family on Himmel Street. Her parents have been taken away to a concentration camp. Liesel steals books. This is her story and the story of the inhabitants of her street when the bombs begin to fall.\r\n\r\nSOME MORE IMPORTANT INFORMATION:\r\n\r\nTHIS NOVEL IS NARRATED BY DEATH.\r\n\r\nIt's a small story, about:\r\na girl\r\nan accordionist\r\nsome fanatical Germans\r\na Jewish fistfighter\r\nand quite a lot of thievery.\r\n\r\nANOTHER THING YOU SHOULD KNOW:\r\n\r\nDEATH WILL VISIT THE BOOK THIEF THREE TIMES.",
                            GenreId = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/914cHl9v7oL._SL1500_.jpg",
                            Title = "The Book Thief"
                        },
                        new
                        {
                            Id = 107,
                            AuthorId = 7,
                            Description = "Harriet Vanger, a scion of one of Sweden’s wealthiest families disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth. He hires Mikael Blomkvist, a crusading journalist recently trapped by a libel conviction, to investigate. He is aided by the pierced and tattooed punk prodigy Lisbeth Salander. Together they tap into a vein of unfathomable iniquity and astonishing corruption.\r\n\r\nAn international publishing sensation, Stieg Larsson’s The Girl with the Dragon Tattoo combines murder mystery, family saga, love story, and financial intrigue into one satisfyingly complex and entertainingly atmospheric novel.",
                            GenreId = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/51rKlSld33L.jpg",
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = 108,
                            AuthorId = 8,
                            Description = "It is the story of four seekers who arrive at a notoriously unfriendly pile called Hill House: Dr. Montague, an occult scholar looking for solid evidence of a \"haunting\"; Theodora, the lighthearted assistant; Eleanor, a friendless, fragile young woman well acquainted with poltergeists; and Luke, the future heir of Hill House. At first, their stay seems destined to be merely a spooky encounter with inexplicable phenomena. But Hill House is gathering its powers—and soon it will choose one of them to make its own.",
                            GenreId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/81HAeHFZ9oL._SL1500_.jpg",
                            Title = "The Haunting of Hill House"
                        },
                        new
                        {
                            Id = 109,
                            AuthorId = 9,
                            Description = "Combining magic, mysticism, wisdom, and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations.\r\n\r\nPaulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, following our dreams.",
                            GenreId = 8,
                            ImageUrl = "https://m.media-amazon.com/images/I/71zHDXu1TaL._SL1500_.jpg",
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 110,
                            AuthorId = 10,
                            Description = "When Jonathan Harker visits Transylvania to help Count Dracula with the purchase of a London house, he makes a series of horrific discoveries about his client. Soon afterwards, various bizarre incidents unfold in England: an apparently unmanned ship is wrecked off the coast of Whitby; a young woman discovers strange puncture marks on her neck; and the inmate of a lunatic asylum raves about the 'Master' and his imminent arrival.\r\n\r\nIn Dracula, Bram Stoker created one of the great masterpieces of the horror genre, brilliantly evoking a nightmare world of vampires and vampire hunters and also illuminating the dark corners of Victorian sexuality and desire.\r\n\r\nThis Norton Critical Edition includes a rich selection of background and source materials in three areas: Contexts includes probable inspirations for Dracula in the earlier works of James Malcolm Rymer and Emily Gerard. Also included are a discussion of Stoker's working notes for the novel and \"Dracula's Guest,\" the original opening chapter to Dracula. Reviews and Reactions reprints five early reviews of the novel. \"Dramatic and Film Variations\" focuses on theater and film adaptations of Dracula, two indications of the novel's unwavering appeal. David J. Skal, Gregory A. Waller, and Nina Auerbach offer their varied perspectives. Checklists of both dramatic and film adaptations are included.\r\n\r\nCriticism collects seven theoretical interpretations of Dracula by Phyllis A. Roth, Carol A. Senf, Franco Moretti, Christopher Craft, Bram Dijkstra, Stephen D. Arata, and Talia Schaffer.\r\n\r\nA Chronology and a Selected Bibliography are included.",
                            GenreId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71dGP-WQ0HL._SL1499_.jpg",
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 111,
                            AuthorId = 11,
                            Description = "It's Christmas time and Holden Caulfield has just been expelled from yet another school...\r\n\r\nFleeing the crooks at Pencey Prep, he pinballs around New York City seeking solace in fleeting encounters—shooting the bull with strangers in dive hotels, wandering alone round Central Park, getting beaten up by pimps and cut down by erstwhile girlfriends. The city is beautiful and terrible, in all its neon loneliness and seedy glamour, its mingled sense of possibility and emptiness. Holden passes through it like a ghost, thinking always of his kid sister Phoebe, the only person who really understands him, and his determination to escape the phonies and find a life of true meaning.\r\n\r\nThe Catcher in the Rye is an all-time classic in coming-of-age literature- an elegy to teenage alienation, capturing the deeply human need for connection and the bewildering sense of loss as we leave childhood behind.\r\n\r\nJ.D. Salinger's (1919–2010) classic novel of teenage angst and rebellion was first published in 1951. The novel was included on Time's 2005 list of the 100 best English-language novels written since 1923. It was named by Modern Library and its readers as one of the 100 best English-language novels of the 20th century. It has been frequently challenged in the court for its liberal use of profanity and portrayal of sexuality and in the 1950's and 60's it was the novel that every teenage boy wants to read.",
                            GenreId = 9,
                            ImageUrl = "https://m.media-amazon.com/images/I/71nXPGovoTL._SL1500_.jpg",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 112,
                            AuthorId = 12,
                            Description = "A searing, postapocalyptic novel destined to become Cormac McCarthy’s masterpiece.\r\n\r\nA father and his son walk alone through burned America. Nothing moves in the ravaged landscape save the ash on the wind. It is cold enough to crack stones, and when the snow falls it is gray. The sky is dark. Their destination is the coast, although they don’t know what, if anything, awaits them there. They have nothing; just a pistol to defend themselves against the lawless bands that stalk the road, the clothes they are wearing, a cart of scavenged food—and each other.\r\n\r\nThe Road is the profoundly moving story of a journey. It boldly imagines a future in which no hope remains, but in which the father and his son, “each the other’s world entire,” are sustained by love. Awesome in the totality of its vision, it is an unflinching meditation on the worst and the best that we are capable of: ultimate destructiveness, desperate tenacity, and the tenderness that keeps two people alive in the face of total devastation.",
                            GenreId = 10,
                            ImageUrl = "https://m.media-amazon.com/images/I/51M7XGLQTBL._SL1200_.jpg",
                            Title = "The Road"
                        },
                        new
                        {
                            Id = 113,
                            AuthorId = 13,
                            Description = "n\"Turning the envelope over, his hand trembling, Harry saw a purple wax seal bearing a coat of arms; a lion, an eagle, a badger and a snake surrounding a large letter 'H'.\"\r\n\r\nHarry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
                            GenreId = 2,
                            ImageUrl = "https://m.media-amazon.com/images/I/91A6EgLH+2L._SL1500_.jpg",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 114,
                            AuthorId = 14,
                            Description = "A masterpiece of rebellion and imprisonment where war is peace freedom is slavery and Big Brother is watching. Thought Police, Big Brother, Orwellian - these words have entered our vocabulary because of George Orwell's classic dystopian novel 1984. The story of one man's Nightmare Odyssey as he pursues a forbidden love affair through a world ruled by warring states and a power structure that controls not only information but also individual thought and memory 1984 is a prophetic haunting tale More relevant than ever before 1984 exposes the worst crimes imaginable the destruction of truth freedom and individuality. With a foreword by Thomas Pynchon. This beautiful paperback edition features deckled edges and french flaps a perfect gift for any occasion",
                            GenreId = 3,
                            ImageUrl = "https://m.media-amazon.com/images/I/51A9t9irmEL._SY445_SX342_.jpg",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 115,
                            AuthorId = 15,
                            Description = "James L.W. West III to include the author’s final revisions and features a note on the composition and text, a personal foreword by Fitzgerald’s granddaughter, Eleanor Lanahan—and a new introduction by two-time National Book Award winner Jesmyn Ward.\r\n\r\nThe Great Gatsby, F. Scott Fitzgerald’s third book, stands as the supreme achievement of his career. First published in 1925, this quintessential novel of the Jazz Age has been acclaimed by generations of readers. The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted “gin was the national drink and sex the national obsession,” it is an exquisitely crafted tale of America in the 1920s.",
                            GenreId = 9,
                            ImageUrl = "https://m.media-amazon.com/images/I/61PxxqzdJPL._SL1491_.jpg",
                            Title = "The Great Gatsby"
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.BookClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeetUpType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("HostId");

                    b.ToTable("BookClubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 101,
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A club for avid readers of classic literature.",
                            HostId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1534580235139-e2ef095e1972?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            MeetUpType = "Online",
                            Name = "Literary Legends"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 102,
                            DateCreated = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discussing all things fantasy and magical worlds.",
                            HostId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1548445929-4f60a497f851?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            MeetUpType = "In-Person",
                            Name = "Fantasy Fanatics"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 103,
                            DateCreated = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exploring science fiction novels and ideas.",
                            HostId = 3,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1701085496588-8f294c8cd063?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            MeetUpType = "Hybrid",
                            Name = "Sci-Fi Society"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 104,
                            DateCreated = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "For fans of thrilling mysteries and crime stories.",
                            HostId = 4,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1673635651187-8206328b0b61?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fG15c3Rlcnl8ZW58MHx8MHx8fDA%3D",
                            MeetUpType = "Online",
                            Name = "Mystery Maniacs"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 105,
                            DateCreated = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A group dedicated to the best romance novels.",
                            HostId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1459623837994-06d03aa27b9b?q=80&w=1332&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            MeetUpType = "In-Person",
                            Name = "Romance Readers"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 106,
                            DateCreated = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delve into historical fiction with fellow enthusiasts.",
                            HostId = 6,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1726768903173-8cac387e97ab?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fGhpc3RvcmljYWwlMjBib29rc3xlbnwwfHwwfHx8MA%3D%3D",
                            MeetUpType = "Online",
                            Name = "Historical Tales"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 107,
                            DateCreated = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intense thrillers and gripping reads every week.",
                            HostId = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1674521659179-b93d7eed75c8?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fHRocmlsbGVyfGVufDB8fDB8fHww",
                            MeetUpType = "Hybrid",
                            Name = "Thriller Thursdays"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 108,
                            DateCreated = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exploring supernatural and paranormal fiction.",
                            HostId = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1485855691614-f7547af0c4c5?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDZ8fHN1cGVybmF0dXJhbHxlbnwwfHwwfHx8MA%3D%3D",
                            MeetUpType = "In-Person",
                            Name = "Supernatural Circle"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 109,
                            DateCreated = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heartwarming stories and everyday adventures.",
                            HostId = 9,
                            ImageUrl = "https://images.unsplash.com/photo-1604960592081-96019492fcc4?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dHJhdmVsJTIwYm9va3xlbnwwfHwwfHx8MA%3D%3D",
                            MeetUpType = "Online",
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 110,
                            DateCreated = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spooky tales and scary reads for brave souls.",
                            HostId = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1595171694538-beb81da39d3e?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTJ8fHRocmlsbGVyfGVufDB8fDB8fHww",
                            MeetUpType = "Hybrid",
                            Name = "Horror House"
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "I loved how Atticus stood up for what was right, even when it wasn’t popular. Truly inspiring.",
                            CreatedDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Yeah, I agree! But I think the real hero was Scout, learning the world through her eyes was fascinating.",
                            CreatedDate = new DateTime(2023, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Bilbo was a true hero in this story, even though he didn’t see himself as one. The Smaug scene was amazing!",
                            CreatedDate = new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Content = "I think Bilbo's journey is so relatable. It shows that you don’t have to be the strongest to do great things.",
                            CreatedDate = new DateTime(2023, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Content = "I found Paul’s transformation overwhelming but fascinating. The world-building in 'Dune' is unreal!",
                            CreatedDate = new DateTime(2023, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            Content = "The politics and the family dynamics are a lot to keep up with, but I’m loving the complexity!",
                            CreatedDate = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 7,
                            Content = "The ending was shocking, but I feel like it was a bit too far-fetched. It didn’t sit well with me.",
                            CreatedDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 8,
                            Content = "I loved how unpredictable it was. It made me rethink everything about the characters.",
                            CreatedDate = new DateTime(2023, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 9,
                            Content = "Darcy’s confession scene is my absolute favorite. The tension between them is perfect.",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 10,
                            Content = "Elizabeth’s wit makes her so charming, but Darcy’s growth is what truly won me over.",
                            CreatedDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 11,
                            Content = "The perspective from Death was haunting, yet it gave the story a deeper emotional layer.",
                            CreatedDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 6,
                            UserId = 12
                        },
                        new
                        {
                            Id = 12,
                            Content = "I agree! Death as a narrator was such a unique touch, and it added a lot of depth to the story.",
                            CreatedDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 6,
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            Content = "The twists were mind-blowing. It kept me on the edge of my seat the entire time.",
                            CreatedDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 7,
                            UserId = 14
                        },
                        new
                        {
                            Id = 14,
                            Content = "I didn’t see the ending coming at all! It’s definitely one of those books you can’t stop thinking about.",
                            CreatedDate = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 7,
                            UserId = 15
                        },
                        new
                        {
                            Id = 15,
                            Content = "I couldn’t put it down, but I was seriously creeped out. The atmosphere was perfect for a horror story.",
                            CreatedDate = new DateTime(2023, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Hill House was so much more than just a haunted house. The psychological elements made it so unsettling.",
                            CreatedDate = new DateTime(2023, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 8,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookClubId = 1,
                            Content = "I just finished 'To Kill a Mockingbird' and can't stop thinking about it! What did everyone else think about Atticus's approach to justice?",
                            CreatedDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            IsPinned = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookClubId = 2,
                            Content = "Who else loved Bilbo's bravery in 'The Hobbit'? That scene with Smaug was incredible!",
                            CreatedDate = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = true,
                            IsPinned = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookClubId = 3,
                            Content = "'Dune' has such an intricate plot! Does anyone else find Paul Atreides's journey inspiring or overwhelming?",
                            CreatedDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            IsPinned = true,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookClubId = 4,
                            Content = "The twists in 'Gone Girl' left me reeling. How did you all interpret the ending?",
                            CreatedDate = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            IsPinned = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookClubId = 5,
                            Content = "Pride and Prejudice is so timeless. What are your favorite Darcy and Elizabeth moments?",
                            CreatedDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = true,
                            IsPinned = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookClubId = 6,
                            Content = "The storytelling in 'The Book Thief' is so unique. What did you think of the perspective from Death?",
                            CreatedDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            IsPinned = true,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            BookClubId = 7,
                            Content = "I'm still thinking about 'The Girl with the Dragon Tattoo.' Who else was blown away by the investigation twists?",
                            CreatedDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            IsPinned = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookClubId = 8,
                            Content = "The eerie atmosphere of 'The Haunting of Hill House' was so vivid! Who else couldn't sleep after reading it?",
                            CreatedDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = true,
                            IsPinned = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookClubId = 9,
                            Content = "I just finished '1984' and I’m still trying to process the dystopian world. How did you interpret Winston’s rebellion?",
                            CreatedDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            IsPinned = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            BookClubId = 10,
                            Content = "I can’t get over the plot twists in 'The Catcher in the Rye.' Did anyone else find Holden’s perspective on life relatable?",
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            IsPinned = false,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 101,
                            Content = "An impactful story that captures the essence of justice and morality.",
                            CreatedDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 102,
                            Content = "A magical adventure filled with charming characters and vivid landscapes.",
                            CreatedDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 103,
                            Content = "Intricate world-building and a gripping tale of power and survival.",
                            CreatedDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 104,
                            Content = "Twists and turns that keep you guessing until the very end.",
                            CreatedDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 105,
                            Content = "A delightful exploration of love, class, and character in Regency England.",
                            CreatedDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookId = 106,
                            Content = "A heart-wrenching yet inspiring story set during a dark time in history.",
                            CreatedDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            BookId = 107,
                            Content = "Dark, gripping, and impossible to put down.",
                            CreatedDate = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookId = 108,
                            Content = "A masterpiece of psychological horror that lingers with you.",
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookId = 109,
                            Content = "A simple yet profound story that inspires self-discovery and hope.",
                            CreatedDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            BookId = 110,
                            Content = "A chilling classic that set the standard for gothic horror.",
                            CreatedDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            BookId = 111,
                            Content = "Raw, emotional, and an unforgettable look into teenage life.",
                            CreatedDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            BookId = 112,
                            Content = "Hauntingly beautiful and thought-provoking.",
                            CreatedDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            BookId = 113,
                            Content = "A magical start to an epic series that captivates readers of all ages.",
                            CreatedDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            BookId = 114,
                            Content = "A chilling and prescient look at a dystopian future.",
                            CreatedDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            BookId = 115,
                            Content = "A beautifully written critique of the American Dream.",
                            CreatedDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            BookId = 101,
                            Content = "While important, the pacing felt uneven, and some characters seemed underdeveloped.",
                            CreatedDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            BookId = 102,
                            Content = "Overly descriptive passages bogged down the story's momentum.",
                            CreatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 18,
                            BookId = 103,
                            Content = "Fascinating ideas, but the dense writing style made it difficult to stay engaged.",
                            CreatedDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 19,
                            BookId = 104,
                            Content = "The characters felt unrelatable and the ending was unsatisfying.",
                            CreatedDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 20,
                            BookId = 105,
                            Content = "While classic, the social satire feels outdated and struggles to resonate with modern audiences.",
                            CreatedDate = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 21,
                            BookId = 114,
                            Content = "The philosophical themes often overshadowed the plot, leaving some parts dry and uninteresting.",
                            CreatedDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 12
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            ImageUrl = "https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHByb2ZpbGV8ZW58MHx8MHx8fDA%3D",
                            JoinedDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            Uid = "UID12345",
                            Username = "alicej"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1689977807477-a579eda91fa2?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fHByb2ZpbGV8ZW58MHx8MHx8fDA%3D",
                            JoinedDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            Uid = "UID67890",
                            Username = "bobsmith"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Mike",
                            ImageUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHByb2ZpbGV8ZW58MHx8MHx8fDA%3D",
                            JoinedDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peluso",
                            Uid = "efo48ObQwUVkUFx4ESFFuAcDz4q1",
                            Username = "charlieb"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Diana",
                            ImageUrl = "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHByb2ZpbGV8ZW58MHx8MHx8fDA%3D",
                            JoinedDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Prince",
                            Uid = "UID13579",
                            Username = "dianap"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Edward",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1675129522693-bd62ffe5e015?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fHByb2ZpbGV8ZW58MHx8MHx8fDA%3D",
                            JoinedDate = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Elric",
                            Uid = "UID11223",
                            Username = "edwarde"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Fiona",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1688740375397-34605b6abe48?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fHByb2ZpbGV8ZW58MHx8MHx8fDA%3D",
                            JoinedDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hill",
                            Uid = "UID44556",
                            Username = "fionah"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "George",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1690579805323-ce7193c0755d?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHx8",
                            JoinedDate = new DateTime(2023, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harrison",
                            Uid = "UID77889",
                            Username = "georgeh"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Hannah",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1693000697180-4e285198d71c?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            JoinedDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Montana",
                            Uid = "UID99101",
                            Username = "hannahm"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Ian",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1689531953275-a5cfcc458931?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE3fHx8ZW58MHx8fHx8",
                            JoinedDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Curtis",
                            Uid = "UID22334",
                            Username = "ianc"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Jill",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1688739379441-fa764e016555?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDh8fHxlbnwwfHx8fHw%3D",
                            JoinedDate = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Valentine",
                            Uid = "UID55667",
                            Username = "jillv"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Kyle",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1689533448099-2dc408030f0f?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI3fHx8ZW58MHx8fHx8",
                            JoinedDate = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reese",
                            Uid = "UID77880",
                            Username = "kyler"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Laura",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1690579804905-86ee0f135a38?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE4fHx8ZW58MHx8fHx8",
                            JoinedDate = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Croft",
                            Uid = "UID99112",
                            Username = "laurac"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Mike",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1689568126014-06fea9d5d341?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI4fHx8ZW58MHx8fHx8",
                            JoinedDate = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tyson",
                            Uid = "UID22344",
                            Username = "miket"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Nina",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1690407617542-2f210cf20d7e?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDM0fHx8ZW58MHx8fHx8",
                            JoinedDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            Uid = "UID55678",
                            Username = "ninaw"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Oscar",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1689747698547-271d2d553cee?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDMyfHx8ZW58MHx8fHx8",
                            JoinedDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilde",
                            Uid = "UID77891",
                            Username = "oscarw"
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VotingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.HasIndex("VotingSessionId");

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 101,
                            UserId = 1,
                            VotingSessionId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 102,
                            UserId = 2,
                            VotingSessionId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 103,
                            UserId = 3,
                            VotingSessionId = 1
                        },
                        new
                        {
                            Id = 4,
                            BookId = 104,
                            UserId = 2,
                            VotingSessionId = 2
                        },
                        new
                        {
                            Id = 5,
                            BookId = 105,
                            UserId = 4,
                            VotingSessionId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookId = 106,
                            UserId = 5,
                            VotingSessionId = 2
                        },
                        new
                        {
                            Id = 7,
                            BookId = 107,
                            UserId = 3,
                            VotingSessionId = 3
                        },
                        new
                        {
                            Id = 8,
                            BookId = 108,
                            UserId = 6,
                            VotingSessionId = 3
                        },
                        new
                        {
                            Id = 9,
                            BookId = 109,
                            UserId = 4,
                            VotingSessionId = 4
                        },
                        new
                        {
                            Id = 10,
                            BookId = 110,
                            UserId = 7,
                            VotingSessionId = 4
                        },
                        new
                        {
                            Id = 11,
                            BookId = 111,
                            UserId = 5,
                            VotingSessionId = 5
                        },
                        new
                        {
                            Id = 12,
                            BookId = 112,
                            UserId = 8,
                            VotingSessionId = 5
                        },
                        new
                        {
                            Id = 13,
                            BookId = 113,
                            UserId = 6,
                            VotingSessionId = 6
                        },
                        new
                        {
                            Id = 14,
                            BookId = 114,
                            UserId = 9,
                            VotingSessionId = 6
                        });
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.VotingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookClubId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("VotingEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("VotingStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("WinningBookId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookClubId");

                    b.HasIndex("WinningBookId");

                    b.ToTable("VotingSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookClubId = 1,
                            IsActive = true,
                            VotingEndDate = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VotingStartDate = new DateTime(2023, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookClubId = 2,
                            IsActive = true,
                            VotingEndDate = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VotingStartDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BookClubId = 3,
                            IsActive = false,
                            VotingEndDate = new DateTime(2023, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VotingStartDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WinningBookId = 107
                        },
                        new
                        {
                            Id = 4,
                            BookClubId = 4,
                            IsActive = true,
                            VotingEndDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VotingStartDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BookClubId = 5,
                            IsActive = false,
                            VotingEndDate = new DateTime(2023, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VotingStartDate = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WinningBookId = 113
                        },
                        new
                        {
                            Id = 6,
                            BookClubId = 6,
                            IsActive = true,
                            VotingEndDate = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VotingStartDate = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookBookClub", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.BookClub", null)
                        .WithMany()
                        .HasForeignKey("BookClubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("HaveReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookClubUser", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.BookClub", null)
                        .WithMany()
                        .HasForeignKey("MemberBookClubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookVotingSession", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("VotingBooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.VotingSession", null)
                        .WithMany()
                        .HasForeignKey("VotingSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Book", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.BookClub", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bookworm_Society_API.Models.User", "Host")
                        .WithMany("HostedBookClubs")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Comment", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Post", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.BookClub", "BookClub")
                        .WithMany("Posts")
                        .HasForeignKey("BookClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookClub");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Review", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Vote", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.VotingSession", "VotingSession")
                        .WithMany("Votes")
                        .HasForeignKey("VotingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");

                    b.Navigation("VotingSession");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.VotingSession", b =>
                {
                    b.HasOne("Bookworm_Society_API.Models.BookClub", "BookClub")
                        .WithMany("VotingSessions")
                        .HasForeignKey("BookClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookworm_Society_API.Models.Book", "WinningBook")
                        .WithMany()
                        .HasForeignKey("WinningBookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BookClub");

                    b.Navigation("WinningBook");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.BookClub", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("VotingSessions");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.User", b =>
                {
                    b.Navigation("HostedBookClubs");
                });

            modelBuilder.Entity("Bookworm_Society_API.Models.VotingSession", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
